kind: ConfigMap
metadata:
  name: configmap-terraria-serversettings-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
apiVersion: v1
data:
  serversettings.txt: > 
    {{ range $key, $value := .Values.terraria.serversettings }}{{$key}}={{ $value }}
    {{ end }}