{{- $RELEASE_NAME := .Release.Name -}}
{{- $RELEASE_NAMESPACE := .Release.Namespace -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-{{ $RELEASE_NAME }}
  namespace: {{ $RELEASE_NAMESPACE }}
  labels:
    app: terraria-{{ $RELEASE_NAME }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: terraria-{{ $RELEASE_NAME }}
  template:
    metadata:
      labels:
        app: terraria-{{ $RELEASE_NAME }}
    spec:
      imagePullSecrets: {{ .Values.imagePullSecrets  }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          name: terraria
          stdin: true
          tty: true
          securityContext: {{ range $key, $value := .Values.securityContext }}
            {{ $key }}: {{ $value }}{{ end }}
          env: {{ range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value }}{{ end }}
          ports:
            - containerPort: 7777
              protocol: TCP
              name: terraria
          volumeMounts: {{ range $key, $value := .Values.persistence }}
            - name: vol-terraria-{{ $key }}
              mountPath: {{ .mountPath }}{{ if .subPath }}
              subPath: {{ .subPath }} {{ end }} {{ end }}
            - name:  vol-terraria-serversettings
              mountPath: /config/serversettings.txt
              subPath: serversettings.txt
          resources: {{ if .Values.resources }}{{ range $key, $value := .Values.resources }}
            {{$key}}: {{ $value }} {{ end }} {{ end }}
      volumes: {{ range $key, $value := .Values.persistence }}
        - name: vol-terraria-{{ $key }}
          persistentVolumeClaim: {{ if $value.existingPersistentVolumeClaim  }}
            claimName: {{ $value.existingPersistentVolumeClaim }} {{ else }}
            claimName: pvc-terraria-{{ $key }}-{{ $RELEASE_NAME }} {{ end }}{{ end }}
        - name: vol-terraria-serversettings
          configMap:
            name: configmap-terraria-serversettings-{{ .Release.Name }}

