{{- $RELEASE_NAME := .Release.Name -}}
{{- $RELEASE_NAMESPACE := .Release.Namespace -}}
{{ range $key, $value := .Values.persistence }}
{{ if not .existingPersistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-terraria-{{ $key }}-{{ $RELEASE_NAME }}
  namespace: {{ $RELEASE_NAMESPACE }}
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: {{ if eq .persistentVolumeClaim.storageClassName "~"}} ""  {{ else }} {{ .persistentVolumeClaim.storageClassName }} {{ end }}
  resources:
    requests:
      storage: {{ .persistentVolumeClaim.storageSize }}
{{ end }}{{ end }}