apiVersion: v1
kind: Service
metadata:
  name: service-terraria-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: terraria-{{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }} {{ if .Values.service.annotations }}
    {{ range $key, $value := .Values.service.annotations }}{{ $key }}: {{ $value | quote }}{{ end }} {{ end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: terraria
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7777
      protocol: TCP
      name: terraria
  selector:
    app: terraria-{{ .Release.Name }}